# 项目启动端口
server:
  port: 8080
  # debug模式
  model: release
  # release 模式
  #model:release /true/false
  enableSwagger: true

# 数据库配置
db:
  dialects: mysql
  host: 10.177.42.165
  port: 3306
  db: devops
  username: root
  password: rootpassword
  charset: utf8
  # 最大空闲数
  maxIdle: 10
  # 最大连接数
  maxOpen: 150

# redis配置
redis:
  address: 10.177.42.165:6379
  password: "admin"